---
output: html_document
---

## Salamander Occupancy - Expert Elicitation Manuscript
RMarkdown File

Created by: Rachel Katz (rachelakatz@gmail.com)
Co-authors: Dan Hocking, Evan Grant, Ben Letcher

Created: Feb 01 2016
Modified from original model.Rmd file - removed manuscript text

Last Updated: March 21 2016

#################### collect and format ovariate data from sheds
```{r install libraries, echo=FALSE, results='hide'}
library(knitr)
library(xtable)
library(dplyr)
library(tidyr)
library(stringr)
library(RPostgreSQL)
library(DBI)
library(ggplot2)
#library(ggthemes)
library(gridExtra)
library(lme4)
```
```{r connect to db, echo=FALSE, results='hide', eval=FALSE}
# load profile locally to play with packrat
source("~/.Rprofile")

# check user name and password
R.home()
print(options('SHEDS_USERNAME'))
print(options('SHEDS_PASSWORD'))

# set connection to database
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, dbname='sheds_new', host='osensei.cns.umass.edu', user=getOption('SHEDS_USERNAME'), password=getOption('SHEDS_PASSWORD'))
db <- src_postgres(dbname='sheds_new', host='osensei.cns.umass.edu', port='5432', user=options('SHEDS_USERNAME'), password=options('SHEDS_PASSWORD'))
```
```{r download covariates from db and save, echo=FALSE, results='hide', eval=FALSE}

# column names: featureid |  variable  | value | zone  | riparian_distance_ft 
# zone = upstream or local
# riparian_distance_ft = 200 or NA
# variable =
# featureid = 
# value = 

# get featureids for the deerfield from jeff
tbl_huc12 <- tbl(db, 'catchment_huc12')
df_huc <- tbl_huc12 %>%
     select(huc12, featureid) %>%
     dplyr::mutate(HUC4=substr(huc12, as.integer(1), as.integer(4)),
                   HUC8=substr(huc12, as.integer(1), as.integer(8)),
                   HUC10=substr(huc12, as.integer(1), as.integer(10))) %>%
     dplyr::filter(substr(huc12, as.integer(1), as.integer(8)) == '01080203')
df_huc <- dplyr::collect(df_huc)
head(df_huc)
plot(df_huc$HUC4)  # 1 basin (CT)
plot(df_huc$HUC10) # 5 subwatersheds
plot(df_huc$featureid)
featureids<-c(df_huc$featureid)

# get the covariates for the featureids
tbl_covariates <- tbl(db, 'covariates')
tbl_covariates <- dplyr::filter(tbl_covariates, featureid %in% featureids ) 
#df_cov_long<-dplyr::collect(tbl_covariates) # this takes ~ 201pm-
#df_covariates<-tidyr::spread(df_cov_long,variable,value)
summary(df_covariates)

df_covariates_m<-as.matrix((df_covariates))
df_covariates_m
#write.csv(df_covariates_m,file="df_covariates.csv")
```
```{r import covariate data, create cov.df, echo=FALSE, results='hide'}

# import saved covariate data from db
deerfield.cov.data<-read.csv("/Users/katz-umass/github_folder/Trout_Salamander_Decisions/Expert_Elicitation/salamander_elicitation_model/df_covariates.csv",fill=TRUE,header=TRUE)

# replace NA's with -999
deerfield.cov.data[is.na(deerfield.cov.data)] <- -999

# select covariates 
covariates<-deerfield.cov.data %>% 
  select(featureid, AreaSqKM,zone,riparian_distance_ft,ann_tmax_c,forest,aug_prcp_mm,slope_pcnt)
str(covariates)

# subset local data (temp)
cov1<-subset(covariates,zone=="local" & ann_tmax_c > -999)
str(cov1) #1088 catchments
ggplot(cov1,aes(cov1$ann_tmax_c)) + geom_histogram(alpha=1,binwidth=.1) + xlim(10,26) + ggtitle("deefield max annual temp")

# subset upstream data (drainage area and precip)
cov2<-subset(covariates, zone=="upstream" & ann_tmax_c > -999)
str(cov2) #1088 catchments
ggplot(cov2,aes(cov2$AreaSqKM)) + geom_histogram(alpha=1, binwidth=20) + ggtitle("deefield drainage area")
ggplot(cov2,aes(cov2$aug_prcp_mm)) + geom_histogram(alpha=1, binwidth=1) + ggtitle("deefield aug upstream precip")

# subset local riparian zone data (forest cover)
cov3<-subset(covariates, riparian_distance_ft == 200 & zone=="local")
str(cov3) #1088 catchments
ggplot(cov3,aes(cov2$forest)) + geom_histogram(alpha=1, binwidth=1) + ggtitle("deefield riparian forest")

# save subset data as cov.df
cov.df<-data.frame(cov2$AreaSqKM,cov2$aug_prcp_mm,cov1$ann_tmax_c,cov2$ann_tmax_c^2,cov2$forest,cov3$forest);colnames(cov.df)<-c("area","prcp","temp","temp2","ufor","rfor")
str(cov.df)

# remove greater than 200km2 drainages
cov.df<-subset(cov.df,cov.df$area <= 200)
str(cov.df)
plot(cov.df)
```

#################### import and analyze expert data 
```{r import expert elicitation data, echo=FALSE, results='hide'}
#import expert data
qall2.data<-read.csv("/Users/katz-umass/github_folder/Trout_Salamander_Decisions/Expert_Elicitation/salamander_elicitation_model/expert_elicitation_questionaire_qall2.csv",stringsAsFactors = TRUE,header=TRUE)
str(qall2.data)
```
```{r plot expert results, echo=FALSE,fig.width=6,fig.height=8}
# remove NA's
qall.data<-subset(qall2.data,mean_reaches>=0)
str(qall.data)

# check for overall variation among experts (across and within species)
p.exsp<-ggplot(qall.data,aes(y=mean_reaches,x=interaction(species,expert_ID), fill=factor(species))) + geom_boxplot() + ylim(0,100) + theme(axis.text.x=element_text(angle=270)) + ggtitle("expert variation across species")
p.ex<-ggplot(qall.data,aes(y=mean_reaches,x=expert_ID,group=factor(expert_ID))) + geom_boxplot() + ylim(0,100) + theme(axis.text.x=element_text(angle=270))+ ggtitle("expert variation within species")
grid.arrange(p.ex,p.exsp)

# region
pd <- position_dodge(0.1)
p2.dfus<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("2") & mean_reaches>=0),aes(expert_ID,mean_reaches,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_errorbar(aes(ymin=lower_reaches, ymax=upper_reaches), width=.1, position=pd) + ylim(0, 100) + theme(legend.position="none") + ggtitle("dfus")
p2.gpor<-ggplot(subset(qall.data,species %in% c("gpor") & question %in% c("2") & mean_reaches>=0),aes(expert_ID,mean_reaches,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_errorbar(aes(ymin=lower_reaches, ymax=upper_reaches), width=.1, position=pd) + ylim(0, 100) + theme(legend.position="none") + ggtitle("gpor")
p2.ebis<-ggplot(subset(qall.data,species %in% c("ebis") & question %in% c("2") & mean_reaches>=0),aes(expert_ID,mean_reaches,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_errorbar(aes(ymin=lower_reaches, ymax=upper_reaches), width=.1, position=pd) + ylim(0, 100) + theme(legend.position="none") + ggtitle("ebis")
grid.arrange(p2.dfus,p2.gpor,p2.ebis,ncol=3)

# drainage
p3.dfus<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("3") & mean_reaches>=0), aes(drainage_area_sqkm,shape=factor(expert_ID))) + geom_point(size=3,aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches))+ ylim(0, 100) + ggtitle("dfus")
p3.gpor<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("3") & mean_reaches>=0), aes(drainage_area_sqkm,shape=factor(expert_ID))) + geom_point(size=3,aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches))+ ylim(0, 100) + ggtitle("gpor")
p3.ebis<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("3") & mean_reaches>=0), aes(drainage_area_sqkm,shape=factor(expert_ID))) + geom_point(size=3,aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches))+ ylim(0, 100) + ggtitle("ebis")
grid.arrange(p3.dfus, p3.gpor, p3.ebis)

# temp
p4.dfus<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("4") & mean_reaches>=0), aes(summer_temp_C,shape=factor(expert_ID))) + geom_point(size=3,aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches))+ ylim(0, 100) + ggtitle("dfus")
p4.gpor<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("4") & mean_reaches>=0), aes(summer_temp_C,shape=factor(expert_ID))) + geom_point(size=3,aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches))+ ylim(0, 100) + ggtitle("gpor")
p4.ebis<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("4") & mean_reaches>=0), aes(summer_temp_C,shape=factor(expert_ID))) + geom_point(size=3,aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches))+ ylim(0, 100) + ggtitle("ebis")
grid.arrange(p4.dfus, p4.gpor, p4.ebis)

# flow
p5.10.dfus<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("5") & mean_reaches>=0 & flow_type==10),aes(flow_year_freq,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches,color=factor(stream_width_m))) + geom_line(aes(y=mean_reaches,group=factor(stream_width_m),color=factor(stream_width_m))) +  ylim(0, 100) +  theme(legend.position="none") + ggtitle("dfus, dry year")
p5.190.dfus<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("5") & mean_reaches>=0 & flow_type==190),aes(flow_year_freq,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches,color=factor(stream_width_m))) + geom_line(aes(y=mean_reaches,group=factor(stream_width_m),color=factor(stream_width_m))) +  ylim(0, 100) +  theme(legend.position="none") + ggtitle("dfus, wet year")

p5.10.gpor<-ggplot(subset(qall.data,species %in% c("gpor") & question %in% c("5") & mean_reaches>=0 & flow_type==10),aes(flow_year_freq,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches,color=factor(stream_width_m))) + geom_line(aes(y=mean_reaches,group=factor(stream_width_m),color=factor(stream_width_m))) +  ylim(0, 100) +  theme(legend.position="none") + ggtitle("gpor, dry year")
p5.190.gpor<-ggplot(subset(qall.data,species %in% c("gpor") & question %in% c("5") & mean_reaches>=0 & flow_type==190),aes(flow_year_freq,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches,color=factor(stream_width_m))) + geom_line(aes(y=mean_reaches,group=factor(stream_width_m),color=factor(stream_width_m))) +  ylim(0, 100) +  theme(legend.position="none") + ggtitle("gpor, wet year")

p5.10.ebis<-ggplot(subset(qall.data,species %in% c("ebis") & question %in% c("5") & mean_reaches>=0 & flow_type==10),aes(flow_year_freq,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches,color=factor(stream_width_m))) + geom_line(aes(y=mean_reaches,group=factor(stream_width_m),color=factor(stream_width_m))) +  ylim(0, 100) +  theme(legend.position="none") + ggtitle("ebis, dry year")
p5.190.ebis<-ggplot(subset(qall.data,species %in% c("ebis") & question %in% c("5") & mean_reaches>=0 & flow_type==190),aes(flow_year_freq,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches,color=factor(stream_width_m))) + geom_line(aes(y=mean_reaches,group=factor(stream_width_m),color=factor(stream_width_m))) +  ylim(0, 100) +  theme(legend.position="none") + ggtitle("ebis, wet year")

grid.arrange(p5.10.dfus,p5.190.dfus,
             p5.10.gpor,p5.190.gpor,
             p5.10.ebis,p5.190.ebis,
             ncol=2)

# riparian and upland forest
p6.0.dfus<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("6") & mean_reaches>=0 & upland_forest==0),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("dfus, 0 upland")
p6.25.dfus<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("6") & mean_reaches>=0 & upland_forest==25),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("dfus, 25 upland")
p6.50.dfus<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("6") & mean_reaches>=0 & upland_forest==50),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("dfus, 50 upland")
p6.75.dfus<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("6") & mean_reaches>=0 & upland_forest==75),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("dfus, 75 upland")
p6.100.dfus<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("6") & mean_reaches>=0 & upland_forest==100),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("dfus, 100 upland")
#grid.arrange(p6.0.dfus,p6.25.dfus,p6.50.dfus,p6.75.dfus,p6.100.dfus)

p6.0.gpor<-ggplot(subset(qall.data,species %in% c("gpor") & question %in% c("6") & mean_reaches>=0 & upland_forest==0),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("gpor, 0 upland")
p6.25.gpor<-ggplot(subset(qall.data,species %in% c("gpor") & question %in% c("6") & mean_reaches>=0 & upland_forest==25),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("gpor, 25 upland")
p6.50.gpor<-ggplot(subset(qall.data,species %in% c("gpor") & question %in% c("6") & mean_reaches>=0 & upland_forest==50),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("gpor, 50 upland")
p6.75.gpor<-ggplot(subset(qall.data,species %in% c("gpor") & question %in% c("6") & mean_reaches>=0 & upland_forest==75),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("gpor, 75 upland")
p6.100.gpor<-ggplot(subset(qall.data,species %in% c("gpor") & question %in% c("6") & mean_reaches>=0 & upland_forest==100),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("gpor, 100 upland")
#grid.arrange(p6.0.gpor,p6.25.gpor,p6.50.gpor,p6.75.gpor,p6.100.gpor)

p6.0.ebis<-ggplot(subset(qall.data,species %in% c("ebis") & question %in% c("6") & mean_reaches>=0 & upland_forest==0),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("ebis, 0 upland")
p6.25.ebis<-ggplot(subset(qall.data,species %in% c("ebis") & question %in% c("6") & mean_reaches>=0 & upland_forest==25),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("ebis, 25 upland")
p6.50.ebis<-ggplot(subset(qall.data,species %in% c("ebis") & question %in% c("6") & mean_reaches>=0 & upland_forest==50),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("ebis, 50 upland")
p6.75.ebis<-ggplot(subset(qall.data,species %in% c("ebis") & question %in% c("6") & mean_reaches>=0 & upland_forest==75),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("ebis, 75 upland")
p6.100.ebis<-ggplot(subset(qall.data,species %in% c("ebis") & question %in% c("6") & mean_reaches>=0 & upland_forest==100),aes(riparian_forest,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_line(aes(y=mean_reaches)) + ylim(0, 100) + theme(legend.position="none") + ggtitle("ebis, 100 upland")
#grid.arrange(p6.0.ebis,p6.25.ebis,p6.50.ebis,p6.75.ebis,p6.100.ebis)

grid.arrange(p6.0.dfus,p6.25.dfus,p6.50.dfus,p6.75.dfus,p6.100.dfus,
             p6.0.gpor,p6.25.gpor,p6.50.gpor,p6.75.gpor,p6.100.gpor,
             p6.0.ebis,p6.25.ebis,p6.50.ebis,p6.75.ebis,p6.100.ebis,ncol=5)

# trout presence
pd <- position_dodge(0.1)
p7.dfus<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("7") & mean_reaches>=0),aes(expert_ID,mean_reaches,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_errorbar(aes(ymin=lower_reaches, ymax=upper_reaches), width=.1, position=pd) + ylim(0, 100) + theme(legend.position="none") + ggtitle("dfus")
p7.gpor<-ggplot(subset(qall.data,species %in% c("gpor") & question %in% c("7") & mean_reaches>=0),aes(expert_ID,mean_reaches,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_errorbar(aes(ymin=lower_reaches, ymax=upper_reaches), width=.1, position=pd) + ylim(0, 100) + theme(legend.position="none") + ggtitle("gpor")
p7.ebis<-ggplot(subset(qall.data,species %in% c("ebis") & question %in% c("7") & mean_reaches>=0),aes(expert_ID,mean_reaches,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_errorbar(aes(ymin=lower_reaches, ymax=upper_reaches), width=.1, position=pd) + ylim(0, 100) + theme(legend.position="none") + ggtitle("ebis")
grid.arrange(p7.dfus,p7.gpor,p7.ebis,ncol=3)

# salamander presence
pd <- position_dodge(0.2)
p8.dfus<-ggplot(subset(qall.data,species %in% c("dfus") & question %in% c("8") & mean_reaches>=0),aes(sal_other,mean_reaches,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches),position=pd) + geom_errorbar(aes(ymin=lower_reaches, ymax=upper_reaches), width=.1, position=pd) + ylim(0, 100) + theme(legend.position="none") +  ggtitle("dfus")
p8.gpor<-ggplot(subset(qall.data,species %in% c("gpor") & question %in% c("8") & mean_reaches>=0),aes(sal_other,mean_reaches,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches),position=pd) + geom_errorbar(aes(ymin=lower_reaches, ymax=upper_reaches), width=.1, position=pd) + ylim(0, 100) + theme(legend.position="none") +  ggtitle("gpor")
p8.ebis<-ggplot(subset(qall.data,species %in% c("ebis") & question %in% c("8") & mean_reaches>=0),aes(sal_other,mean_reaches,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches),position=pd) + geom_errorbar(aes(ymin=lower_reaches, ymax=upper_reaches), width=c(confidence_reaches), position=pd) + ylim(0, 100) + theme(legend.position="none") +  ggtitle("ebis")
grid.arrange(p8.dfus,p8.gpor,p8.ebis,ncol=3)
```
```{r calculate betas, echo=FALSE}

# convert mean_reaches to p (occupancy = mean_reaches/100) and/or logitp
qall.data$p<-qall.data$mean_reaches/100
qall.data$p[qall.data$p==0]<-0.01 # trick to avoid NA's
qall.data$p[qall.data$p==1]<-0.99 # trick to avoid NA's

qall.data$logit.p<-log(qall.data$p/(1-qall.data$p))
plot(density(qall.data$logit.p))
ggplot(qall.data,aes(x=logit.p,y=p)) + geom_point()

ggplot(qall.data,aes(x=question,y=logit.p,group=interaction(expert_ID,question),fill=factor(expert_ID))) + geom_boxplot()
ggplot(qall.data,aes(x=question,y=p,group=interaction(expert_ID,question),fill=factor(expert_ID))) + geom_boxplot()

# subset data for each species
qall.dfus<-subset(qall.data,qall.data$species=="dfus" & qall.data$expert_ID>=0 & qall.data$p>=0)
qall.gpor<-subset(qall.data,qall.data$species=="gpor" & qall.data$expert_ID>=0 & qall.data$p>=0)
qall.ebis<-subset(qall.data,qall.data$species=="ebis" & qall.data$expert_ID>=0 & qall.data$p>=0)

# run logistic linear regression with random effect of expert for each species
lm1.dfus<-lmer(logit.p ~ log((s.area)+1) + s.temp +I(s.temp^2) + s.flow + s.freq + s.ripa + s.upla + s.ripa*s.upla + s.fish + s.ebis + s.gpor + (1|expert_ID),data = qall.dfus)
lm1.ebis<-lmer(logit.p ~ log((s.area)+1) + s.temp +I(s.temp^2) + s.flow + s.freq + s.ripa + s.upla + s.ripa*s.upla + s.fish + s.dfus + s.gpor + (1|expert_ID),data = qall.ebis)
lm1.gpor<-lmer(logit.p ~ log((s.area)+1) + s.temp +I(s.temp^2) + s.flow + s.freq + s.ripa + s.upla + s.ripa*s.upla + s.fish + s.ebis + s.dfus + (1|expert_ID),data = qall.gpor)

# view model results
summary(lm1.dfus); plot(lm1.dfus) 
summary(lm1.ebis); plot(lm1.ebis)
summary(lm1.gpor); plot(lm1.gpor) 

# save predicted values and residuals for each species
qall.dfus$pred <- predict(lm1.dfus,qall.dfus)
qall.dfus$resid<- resid(lm1.dfus)
qall.dfus$predp<-1/(1+exp(-qall.dfus$pred))
qall.ebis$pred <- predict(lm1.ebis,qall.ebis)
qall.ebis$resid<- resid(lm1.ebis)
qall.ebis$predp<-1/(1+exp(-qall.ebis$pred))
qall.gpor$pred <- predict(lm1.gpor,qall.gpor)
qall.gpor$resid<- resid(lm1.gpor)
qall.gpor$predp<-1/(1+exp(-qall.gpor$pred))

# plot model fit (actual vs. predicted)
p1<-ggplot(qall.dfus, aes(predp,p), colour="black") + geom_point() + stat_smooth(method="lm") + ggtitle('dfus')
p2<-ggplot(qall.ebis, aes(predp,p), colour="black") + geom_point() + stat_smooth(method="lm") + ggtitle('ebis')
p3<-ggplot(qall.gpor, aes(predp,p), colour="black") + geom_point() + stat_smooth(method="lm") + ggtitle('gpor')
grid.arrange(p1, p2, p3)

# plot residuals by question 
p4<-ggplot(qall.dfus, aes(question,resid), colour="black") + geom_point() + ggtitle('dfus')
p5<-ggplot(qall.ebis, aes(question,resid), colour="black") + geom_point() + ggtitle('ebis')
p6<-ggplot(qall.gpor, aes(question,resid), colour="black") + geom_point() + ggtitle('gpor')
grid.arrange(p4, p5, p6)

# plot residuals by question and expert
p7<-ggplot(qall.dfus, aes(interaction(expert_ID,question),resid, fill=factor(expert_ID))) + geom_boxplot() + ggtitle('dfus') 
p8<-ggplot(qall.ebis, aes(interaction(expert_ID,question),resid, fill=factor(expert_ID))) + geom_boxplot()  + ggtitle('ebis')
p9<-ggplot(qall.gpor, aes(interaction(expert_ID,question),resid, fill=factor(expert_ID))) + geom_boxplot() + ggtitle('gpor')
grid.arrange(p7, p8, p9)

# make new df with predicted and residuals 
qall.new<-rbind(qall.dfus,qall.ebis,qall.gpor)

# plot relations between predicted occ and factors
dodge=position_dodge(width=0.5)  

# q3 - stream size
p10<-ggplot(subset(qall.new,qall.new$question==3),aes(s.area,predp,shape=factor(expert_ID),color=factor(species))) + geom_point() + geom_line() + ylim(0,1) + ylab("predicted prob occupancy")+ xlab("catchment drainage area, km2")

# q4 - stream temp
p11<-ggplot(subset(qall.new,qall.new$question==4),aes(s.temp,predp,shape=factor(expert_ID),color=factor(species))) + geom_point()+ geom_line()+ ylim(0,1) + ylab("predicted prob occupancy")+ xlab("mean summer temp, C")

# q5 - streamflow
p13.dry.small<-ggplot(subset(qall.new,qall.new$question==5 & flow_type==10 & stream_width_m==2),aes(flow_year_freq,predp,shape=factor(expert_ID),color=factor(species))) + geom_point()+ geom_line() + ylim(0,1) + ylab("predicted prob occupancy")+ xlab("frequency of dry years") + ggtitle("small stream, dry")
p13.wet.small<-ggplot(subset(qall.new,qall.new$question==5 & flow_type==190 & stream_width_m==2),aes(flow_year_freq,predp,shape=factor(expert_ID),color=factor(species))) + geom_point()+ geom_line() + ylim(0,1) + ylab("predicted prob occupancy")+ xlab("frequency of wet years") + ggtitle("small stream, wet")
p13.dry.medium<-ggplot(subset(qall.new,qall.new$question==5 & flow_type==10 & stream_width_m==2),aes(flow_year_freq,predp,shape=factor(expert_ID),color=factor(species))) + geom_point()+ geom_line() + ylim(0,1) + ylab("predicted prob occupancy")+ xlab("frequency of dry years") + ggtitle("medium stream, dry")
p13.wet.medium<-ggplot(subset(qall.new,qall.new$question==5 & flow_type==190 & stream_width_m==2),aes(flow_year_freq,predp,shape=factor(expert_ID),color=factor(species))) + geom_point()+ geom_line() + ylim(0,1) + ylab("predicted prob occupancy")+ xlab("frequency of wet years") + ggtitle("medium stream, wet")
grid.arrange(p13.dry.small,p13.wet.small,p13.dry.medium,p13.wet.medium)

# q6 - forest cover
p12.100<-ggplot(subset(qall.new,qall.new$question==6 & upland_forest==100),aes(s.ripa,predp,shape=factor(expert_ID),color=factor(species))) + geom_point()+ geom_line() + ylim(0,1) + ylab("predicted prob occupancy")+ xlab("percentriparian") + ggtitle("100% upland forest")
p12.75<-ggplot(subset(qall.new,qall.new$question==6 & upland_forest==75),aes(s.ripa,predp,shape=factor(expert_ID),color=factor(species))) + geom_point()+ geom_line() + ylim(0,1) + ylab("predicted prob occupancy")+ xlab("percentriparian") + ggtitle("75% upland forest")
p12.50<-ggplot(subset(qall.new,qall.new$question==6 & upland_forest==50),aes(s.ripa,predp,shape=factor(expert_ID),color=factor(species))) + geom_point()+ geom_line() + ylim(0,1) + ylab("predicted prob occupancy")+ xlab("percentriparian") + ggtitle("50% upland forest")
p12.25<-ggplot(subset(qall.new,qall.new$question==6 & upland_forest==25),aes(s.ripa,predp,shape=factor(expert_ID),color=factor(species))) + geom_point()+ geom_line() + ylim(0,1) + ylab("predicted prob occupancy")+ xlab("percentriparian") + ggtitle("25% upland forest")
p12.0<-ggplot(subset(qall.new,qall.new$question==6 & upland_forest==0),aes(s.ripa,predp,shape=factor(expert_ID),color=factor(species))) + geom_point()+ geom_line() + ylim(0,1) + ylab("predicted prob occupancy")+ xlab("percentriparian") + ggtitle("0% upland forest")
grid.arrange(p12.100,p12.75,p12.50,p12.25,p12.0)

# q7 - brook trout
pd <- position_dodge(0.1)
p14<-ggplot(subset(qall.new,qall.new$question==7),aes(expert_ID,predp,shape=factor(expert_ID))) + geom_point(aes(y=mean_reaches)) + geom_errorbar(aes(ymin=lower_reaches, ymax=upper_reaches), width=.1, position=pd) + ylim(0, 100)  + ggtitle("0% upland forest")
p14


```

```{r export betas, echo=FALSE, results='hide'}
# create list for betas
betas<-list()
betas$dfus<-summary(lm1.dfus)
betas$gpor<-summary(lm1.gpor)
betas$ebis<-summary(lm1.ebis)
betas.coef<-data.frame(dfus=print(betas$dfus$coefficients[,1:2]),gpor=print(betas$gpor$coefficients[,1:2]),ebis=print(betas$ebis$coefficients[,1:2]))
betas.coef$min<-c(NA,
                  min(log(qall.data$drainage_area_sqkm+1)),
                  min(qall.data$summer_temp_C),
                  min(qall.data$summer_temp_C^2),
                  min(qall.data$flow_type),
                  min(qall.data$flow_year_freq),
                  min(qall.data$riparian_forest),
                  min(qall.data$upland_forest),
                  min(qall.data$trout_presence),
                  min(qall.data$ebis_presence),
                  min(qall.data$gpor_presence),
                  min(qall.data$riparian*qall.data$upland))
betas.coef$max<-c(NA,
                  max(log(qall.data$drainage_area_sqkm+1)),
                  max(qall.data$summer_temp_C),
                  max(qall.data$summer_temp_C^2),
                  max(qall.data$flow_type),
                  max(qall.data$flow_year_freq),
                  max(qall.data$riparian_forest),
                  max(qall.data$upland_forest),
                  max(qall.data$trout_presence),
                  max(qall.data$ebis_presence),
                  max(qall.data$gpor_presence),
                  max(qall.data$riparian*qall.data$upland))
betas.coef$mean<-c(NA,
                  mean(qall.data$drainage),
                  mean(qall.data$temp),
                  mean(qall.data$temp^2),
                  mean(qall.data$riparian),
                  mean(qall.data$upland),
                  mean(qall.data$trout),
                  mean(qall.data$riparian*qall.data$upland))
betas.coef$sd<-c(NA,
                  sd(qall.data$drainage),
                  sd(qall.data$temp),
                  sd(qall.data$temp^2),
                  sd(qall.data$riparian),
                  sd(qall.data$upland),
                  sd(qall.data$trout),
                  sd(qall.data$riparian*qall.data$upland))
                  
betas.coef$s.min<-c(NA,
                  min(log(qall.data$s.drainage+1)),
                  min(qall.data$s.temp),
                  min(qall.data$s.temp^2),
                  min(qall.data$s.riparian),
                  min(qall.data$s.upland),
                  min(qall.data$trout),
                  min(qall.data$s.riparian*qall.data$s.upland))
betas.coef$s.max<-c(NA,
                  max(log(qall.data$s.drainage+1)),
                  max(qall.data$s.temp),
                  max(qall.data$s.temp^2),
                  max(qall.data$s.riparian),
                  max(qall.data$s.upland),
                  max(qall.data$trout),
                  max(qall.data$s.riparian*qall.data$s.upland))
betas.coef$s.mean<-c(NA,
                  mean(log(qall.data$s.drainage+1)),
                  mean(qall.data$s.temp),
                  mean(qall.data$s.temp^2),
                  mean(qall.data$s.riparian),
                  mean(qall.data$s.upland),
                  mean(qall.data$trout),
                  mean(qall.data$s.riparian*qall.data$s.upland))
betas.coef$s.sd<-c(NA,
                  sd(log(qall.data$s.drainage+1)),
                  sd(qall.data$s.temp),
                  sd(qall.data$s.temp^2),
                  sd(qall.data$s.riparian),
                  sd(qall.data$s.upland),
                  sd(qall.data$trout),
                  sd(qall.data$s.riparian*qall.data$s.upland))
colnames(betas.coef)<-c("defu.mean","defu.sd","gypo.mean","gypo.sd","eubi.mean","eubi.sd","min.cov","max.cov","mean.cov","sd.cov","min.scov","max.scov","mean.scov","sd.scov")
predictor.name<-c("int","drainage","temp","temp2","riparian","upland","trout","riparian.upland.int")
betas.coef$predictor<-predictor.name
write.csv(betas.coef,file="out_betas.csv",col.names=TRUE,row.names=TRUE)
print(betas.coef)
```

```{r plot betas, echo=FALSE, results='hide', fig.height=8, fig.width=5}

betas.mean<-c(betas.coef[1:8,"defu.mean"],betas.coef[1:8,"gypo.mean"],betas.coef[1:8,"eubi.mean"])
betas.sd<-c(betas.coef[1:8,"defu.sd"],betas.coef[1:8,"gypo.sd"],betas.coef[1:8,"eubi.sd"])
betas.sp<-c(rep("defu",8),rep("gypo",8),rep("eubi",8))
betas.name<-c(rep(predictor.name,3))

all.betas<-data.frame(betas.mean,betas.sd,betas.sp,betas.name)
#all.betas

dodge=position_dodge(width=0.5)  
ggplot(all.betas,aes(y=betas.mean,x=betas.name,shape=factor(betas.sp))) + geom_point(aes(shape=betas.sp),position=dodge,size=2) +
geom_errorbar(aes(y=betas.mean,ymin=betas.mean-betas.sd, ymax=betas.mean+betas.sd),size=.5,position=dodge,width=0) +
coord_flip()    

```



```{r standarize cov.df, echo=FALSE, results='hide', eval=FALSE}
# import betas (with range in covariates in survey)
beta.data<-read.csv("/Users/katz-umass/github_folder/Trout_Salamander_Decisions/Expert_Elicitation/salamander_elicitation_model/out_betas.csv",fill=TRUE,header=TRUE)
beta.data

cov.area.std<-(cov$cov.area.AreaSqKM-beta.data[beta.data$predictor=="drainage","mean.cov"])/beta.data[beta.data$predictor=="drainage","sd.cov"]
cov.temp.std<-(cov$cov.temp.ann_tmax_c-beta.data[beta.data$predictor=="temp","mean.cov"])/beta.data[beta.data$predictor=="temp","sd.cov"]
cov.temp2.std<-(cov$cov.temp.ann_tmax_c^2-beta.data[beta.data$predictor=="temp2","mean.cov"])/beta.data[beta.data$predictor=="temp2","sd.cov"]
cov.upla.std<-(cov$cov.temp.forest-beta.data[beta.data$predictor=="upland","mean.cov"])/beta.data[beta.data$predictor=="upland","sd.cov"]
cov.ripa.std<-(cov$cov.ripa.forest-beta.data[beta.data$predictor=="riparian","mean.cov"])/beta.data[beta.data$predictor=="riparian","sd.cov"]

# create matrix of std.covariates
cov.df.std<-cbind(log(cov.area.std+1))

cov.std.m<-cbind(cov.temp.std)
cov.std.m<-cbind(cov.temp2.std)
cov.std.m<-cbind(cov.temp.std,cov.temp2.std)

cov.std.m<-cbind(cov.upla.std)
cov.std.m<-cbind(cov.ripa.std)
cov.std.m<-cbind(cov.ripa.std,cov.upla.std,cov.ripa.upla.std)

cov.std.m<-cbind(log(cov.area.std+1),cov.temp.std,cov.temp2.std,cov.ripa.std,cov.upla.std,cov.ripa.upla.std)

cov.std.m<-as.matrix(cov.std.m,ncols=6,nrows=985)
str(cov.std.m)
#,cov.temp.std,cov.temp.std^2,cov.upla.std,cov.ripa.std)

# create a vector of betas for each species
dfus.betas<-c(beta.data$defu.mean[2:6],beta.data$defu.mean[8])
#,beta.data$defu.mean[6],beta.data$defu.mean[5])
ebis.betas<-c(beta.data$eubi.mean[2:6],beta.data$eubi.mean[8])
#,beta.data$eubi.mean[6],beta.data$eubi.mean[5])
gpor.betas<-c(beta.data$gypo.mean[2:6],beta.data$gypo.mean[8])
#,beta.data$gypo.mean[6],beta.data$gypo.mean[5])

# calculate probability of occupancy using logit link function
logit.p.dfus<- beta.data$defu.mean[1] + rowSums(cov.std.m * dfus.betas)  
pr_occ.dfus<-1/(1+exp(-(logit.p.dfus)))
logit.p.ebis<- beta.data$eubi.mean[1] + rowSums(cov.std.m * ebis.betas)   
pr_occ.ebis<-1/(1+exp(-(logit.p.ebis)))
logit.p.gpor<- beta.data$gypo.mean[1] + rowSums(cov.std.m * gpor.betas)   
pr_occ.gpor<-1/(1+exp(-(logit.p.gpor)))

cov$dfus_pr_occ<-pr_occ.dfus
cov$ebis_pr_occ<-pr_occ.ebis
cov$gpor_pr_occ<-pr_occ.gpor

ggplot(cov, aes(cov.area.AreaSqKM,y=value)) +
  geom_point(aes(y=dfus_pr_occ,col="blue")) +
  geom_point(aes(y=ebis_pr_occ,col="red")) +
  geom_point(aes(y=gpor_pr_occ,col="green"))

ggplot(cov, aes(cov.temp.forest,y=value)) +
  geom_point(aes(y=dfus_pr_occ,col="blue")) +
  geom_point(aes(y=ebis_pr_occ,col="red")) +
  geom_point(aes(y=gpor_pr_occ,col="green"))

ggplot(cov, aes(cov.ripa.forest,y=value)) +
  geom_point(aes(y=dfus_pr_occ,col="blue")) +
  geom_point(aes(y=ebis_pr_occ,col="red")) +
  geom_point(aes(y=gpor_pr_occ,col="green"))

ggplot(cov, aes(cov.ripa.forest,y=value)) +
  geom_point(aes(y=dfus_pr_occ,col="blue")) +
  geom_point(aes(y=ebis_pr_occ,col="red")) +
  geom_point(aes(y=gpor_pr_occ,col="green"))

ggplot(cov, aes(cov.temp.ann_tmax_c,y=value)) +
  geom_point(aes(y=dfus_pr_occ,col="blue")) +
  geom_point(aes(y=ebis_pr_occ,col="red")) +
  geom_point(aes(y=gpor_pr_occ,col="green"))

```






```{r occ.model.sim1, echo=FALSE, results='hide',eval=FALSE}
no.catchments=100
no.species=1
no.simulations=20 # number of experts

# create empty vectors and matrices for storing output
sim1.data<-catchment.data.sub1[1:no.catchments,]
pr.occupancy<-alpha<-matrix(rep(NA,no.catchments*no.species*no.simulations))
dim(alpha)<-dim(pr.occupancy)<-c(no.catchments,no.species,no.simulations)
mean.pr.occupancy<-sd.pr.occupancy<-matrix(rep(NA,no.catchments*no.species),nrow=no.catchments,ncol=no.species)
intercept<-b1<-b2<-rep(NA,no.simulations)

# create parameter uncertainty 
# need to calcuate odd-ratios from expert elicitation
# unsure how to add variance/sd in odd-ratios
intercept[1:no.simulations]<-rnorm(no.simulations,mean=log(0.5/(1-0.5)),sd=0.1) # 0.5 average occupancy
b1[1:no.simulations]<-rnorm(no.simulations,log(10),sd=0.1) # 5x more likely to occur for every 1 percent increase in forest cover
b2[1:no.simulations]<-rnorm(no.simulations,log(0.90),sd=0.1) # 10x less likely to occur for every 1 sqkm increase in drainage area

for (species in 1:no.species){
  for (catchment in 1:no.catchments){
    for (sim in 1:no.simulations){
      alpha[catchment,species,sim]<-
      intercept[sim] + b1[sim]*sim1.data$MEAN[catchment] + b2[sim]*sim1.data$AreaSqKM[catchment]
      #+ regional.effect (provinces) 
      #+ stream.temp (july mean or annual max) 
      #+ stream.flow (precip x drainage area; high or low-flow magnitude) 
      #+ riparian.forest (within 30m of riparian)  
      #+ upland.forest (outside of 30m riparian) 
      #+ riparian.forest x upland.forest (interaction term) 
      #+ fish.presence (brook trout; yes or no) 
      #+ residual variance
    pr.occupancy[catchment,species,sim]<-exp(alpha[catchment,species,sim])/(exp(alpha[catchment,species,sim])+1) 
  } # sim
    mean.pr.occupancy[catchment,species]<-mean(pr.occupancy[catchment,species,1:no.simulations])
    sd.pr.occupancy[catchment,species]<-sd(pr.occupancy[catchment,species,1:no.simulations])
 }
}

#head(alpha)
#head(pr.occupancy)
```


```{r plot.occ,echo=FALSE, results="hide",include=FALSE}
par(mfrow=c(2,2))
#plot(sim1.data$MEAN,sim1.data$AreaSqKM,xlab="percent upstream forest",ylab="drainage area")
plot(mean.pr.occupancy~sim1.data$MEAN,ylim=c(0,1),xlab="percent upstream forest")
plot(mean.pr.occupancy~sim1.data$AreaSqKM,ylim=c(0,1),xlab="drainage area")
plot(sd.pr.occupancy~sim1.data$MEAN,ylim=c(-2,2),xlab="percent upstream forest")
plot(sd.pr.occupancy~sim1.data$AreaSqKM,ylim=c(-2,2),xlab="drainage area")
```







